#!/usr/bin/env python3
"""Compare Lethe's NLP suggestion lane across the English spaCy models, and
write the report to docs/nlp-model-comparison.md.

The comparison measures the *suggestion lane only* (nlp_suggester.suggest()):
the candidate people/organisations surfaced for the human reviewer, on top of
the entity dictionary and pattern detectors. Every row is one spaCy model as
selected in the app's Settings page; the "before" baseline is the small model
that shipped previously, the "after" rows are the added md/lg models.

The Chinese half of the report comes from tools/zh_ner_eval.py, which this
script imports and appends — one doc generator, so the two never drift.

Run:  python tools/compare_nlp_models.py
Needs: the [nlp] extras installed plus whichever models you want measured
(missing models are shown as "n/a", and the Chinese bake-off fetches the
catalogue models it needs the way Settings would). Uses a throwaway
LETHE_DATA_DIR unless one is already set.
"""
from __future__ import annotations

import os
import re
import sys
import tempfile
import time

# A scratch data dir so model switches (and the Chinese-model downloads the
# bake-off needs) don't touch real data. Set LETHE_DATA_DIR to reuse one.
os.environ.setdefault("LETHE_DATA_DIR", tempfile.mkdtemp(prefix="lethe-nlp-cmp-"))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lethe import nlp_suggester  # noqa: E402

import zh_ner_eval  # noqa: E402  (same tools/ dir — one doc generator)

SAMPLES = {
    "en": os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "samples", "nlp-sample-en.txt"),
}
GOLD = {
    "en": ["John Smith", "Jane Doe", "Michael Chen", "Sarah Whitfield",
           "Acme Capital Partners", "Meridian Holdings Pte Ltd",
           "Riverstone Energy", "Northwind Asset Management",
           "Sinovac Biotech", "WuXi AppTec", "Priya Raghunathan",
           "Lars Andersen", "Bharti Airtel", "Okonkwo"],
}


def _baseline_row(code: str, text: str, gold: list[str]):
    """The pre-expansion (v1.3.1) detection path for a language, measured the
    same way as the new rows so the "before" column is a true baseline."""
    # v1.3.1 English was Presidio + en_core_web_sm — the same path and model as
    # the bundled offline model, so the sm row below IS the before/after
    # baseline.
    return None, None, None


def _surfaces(text: str, spans) -> list[str]:
    return [text[s:e].strip() for s, e, _t in spans if text[s:e].strip()]


def _spacy_version() -> str:
    try:
        import spacy
        return spacy.__version__
    except Exception:  # noqa: BLE001
        return "n/a"


def _match(gold: list[str], surfaces: list[str]) -> tuple[set[str], int]:
    matched, fp = set(), 0
    for s in surfaces:
        if any(g in s or s in g for g in gold):
            matched.update(g for g in gold if g in s or s in g)
        else:
            fp += 1
    return matched, fp


def main() -> int:
    report = [
        "# NLP model comparison — detection models",
        "",
        "Every table measures the app's real code path (`nlp_suggester._analyze` / `suggest()`",
        "— the **suggestion lane only**: candidate people/counterparties surfaced for the human",
        "reviewer, before the dictionary and pattern detectors).",
        "",
        "The **English** section below is generated by `tools/compare_nlp_models.py` against",
        "`samples/nlp-sample-en.txt`. “Before” is the pre-expansion (v1.3.1) detection path:",
        "Presidio + `en_core_web_sm` — still the bundled offline model, so the `sm` row is its",
        "own before/after baseline; the added `md`/`lg` rows are the expanded catalogue.",
        "",
        "The **Chinese** sections (further down, generated by `tools/zh_ner_eval.py`) cover",
        "what the business actually cares about — people, organisations and school names — on",
        "two sets: a due-diligence memo in `samples/nlp-sample-zh.txt`, and the 1343-sentence",
        "public CLUENER2020 dev split. They are what the Chinese model *selection* rests on:",
        "the memo alone is small enough that the spaCy models saturate it.",
        "",
        f"Environment: spaCy {_spacy_version()} · Presidio loaded per language/model · "
        f"the active model per language is persisted in the app data directory "
        f"(`nlp_models.json`).",
        "",
    ]

    for code, path in SAMPLES.items():
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        gold = GOLD[code]
        table, details = [], []
        base_row, base_matched, base_surfaces = _baseline_row(code, text, gold)
        if base_row:
            table.append(base_row)
            details += [
                "### v1.3.1 baseline (`zh_core_web_sm`, spaCy NER only)",
                "",
                f"- Detected {len(base_surfaces)} spans, `{len(base_matched)}/{len(gold)}` gold "
                f"entities matched ({len(base_matched)/len(gold):.0%}).",
                "- Gold entities **missed**: " + (
                    ", ".join(f"`{g}`" for g in gold if g not in base_matched)
                    if len(base_matched) < len(gold) else "—"),
                "",
            ]
        for lang in nlp_suggester.LANGUAGES:
            if lang["code"] != code:
                continue
            for m in lang["models"]:
                name = m["name"]
                if m.get("hf_id"):
                    # Not a spaCy wheel; the Chinese bake-off below covers it
                    # through the app's real code path.
                    continue
                if not nlp_suggester.is_installed(name):
                    table.append(f"| `{name}` | n/a — not installed in this environment |")
                    continue
                nlp_suggester.set_active_model(code, name)
                t0 = time.perf_counter()
                spans = nlp_suggester.suggest(text)
                dt = time.perf_counter() - t0
                surfaces = _surfaces(text, spans)
                matched, fp = _match(gold, surfaces)
                recall = len(matched) / len(gold)
                table.append(
                    f"| `{name}` | {len(spans)} | {len(set(surfaces))} | {len(matched)}/{len(gold)} "
                    f"| {recall:.0%} | {fp} | {dt:.1f}s |")
                details += [
                    f"### `{name}`",
                    "",
                    f"- Detected {len(spans)} spans, {len(set(surfaces))} distinct surfaces, "
                    f"`{len(matched)}/{len(gold)}` gold entities matched ({recall:.0%}), "
                    f"{fp} false positives.",
                    "- Gold entities **detected**: " + (
                        ", ".join(f"`{g}`" for g in gold if g in matched) if matched else "—"),
                    "- Gold entities **missed**: " + (
                        ", ".join(f"`{g}`" for g in gold if g not in matched) if len(matched) < len(gold) else "—"),
                    "- Sample surfaces: " + (", ".join(f"`{s}`" for s in surfaces[:12]) if surfaces else "—"),
                    "",
                ]
        report += [
            f"## {code.upper()} — `{os.path.basename(path)}`",
            "",
            f"Gold entities ({len(gold)}): " + ", ".join(f"`{g}`" for g in gold),
            "",
            "| Model | Spans | Distinct | Gold matched | Recall | False positives | Time |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ] + table + ["", "Per-model detail:", ""] + details

    report += zh_ner_eval.report()

    report += [
        "## Findings",
        "",
        "- **English — recall rises with model size.** On the 14 gold entities the shipped small",
        "  model recovers 12 (86%), `en_core_web_md` 13 (93%) and `en_core_web_lg` 14 (100%): the",
        "  added models are what pick up the non-Anglo names and suffix-less company names",
        "  (`Priya Raghunathan`, `Bharti Airtel`, `WuXi AppTec`) that sm misses. `lg` also surfaces",
        "  a few more false positives (job titles such as `General Counsel`, section headings) —",
        "  acceptable for a reviewer-facing suggestion lane, but `md` is the better",
        "  recall/noise trade-off for English.",
        "- **Chinese — spaCy tops out well below the RaNER model.** On the due-diligence memo",
        "  the spaCy catalogue saturates (sm 85%, md 96%, lg 93%, trf 100% of 27 gold entities),",
        "  but on the 1343-sentence CLUENER2020 dev split the gap is plain: `zh_core_web_lg`",
        "  recalls 72% of people and 58% of organisations, `zh_core_web_trf` 81% / 71%, and the",
        "  RaNER checkpoint 93% / 80% — with *fewer* false positives than lg (235 vs 320).",
        "  School names land in RaNER's ORG class, and all six schools in the memo are found.",
        "- **RaNER is now in the Chinese catalogue** as `zh_raner_base_generic`",
        "  (Apache-2.0, ~409 MB, downloaded from Settings like any other model; it needs",
        "  CPU-only PyTorch, ~200 MB). `shibing624/bert4ner-base-chinese` was measured and",
        "  rejected — its organisation recall (52%) is below `zh_core_web_lg`; the best row in",
        "  the bake-off, `uer/...-cluener2020-chinese` (91% / 91%), declares no licence, so it",
        "  cannot ship with an Apache-2.0 application.",
        "- **`lg` is the default for English and Chinese; RaNER is a one-click upgrade.** Install",
        "  `lg` once (Settings, or the `[nlp-models]` extra) and detection uses it automatically",
        "  — no further switch needed, which is what maximises recall out of the box; until it is",
        "  installed, the bundled `en_core_web_sm` keeps English working fully offline. For",
        "  Chinese, download RaNER and it becomes the active model straight away. A Settings",
        "  choice always wins, so switching back to `sm`/`md` (smaller download, faster) stays",
        "  available and takes effect on the next document.",
        "- **Not measured here:** `en_core_web_trf` (transformer) — it is offered in Settings but",
        "  needs PyTorch on top of the wheel, so it was left out of this comparison; expect",
        "  slower, higher-recall English detection on the same pipeline.",
        "",
    ]

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "nlp-model-comparison.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(report))
    print("\n".join(report))
    print(f"\n-> wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
